/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\renderer\theme\peaksTheme.ts
 * Command: astryx theme build src\renderer\theme\peaksTheme.ts --out src\renderer\theme\peaks.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/// <reference path="./peaks.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const peaksTheme: DefinedTheme;
