/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\renderer\theme\peaksTheme.ts
 * Command: astryx theme build src\renderer\theme\peaksTheme.ts --out src\renderer\theme\peaks.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/**
 * peaks theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { peaksTheme } from './peaks';
 *   import './peaks.css';
 */
export const peaksTheme = {
  name: 'peaks',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.3125rem",
    "--font-size-3xs": "0.375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.5625rem",
    "--font-size-sm": "0.6875rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.3125rem",
    "--font-size-2xl": "1.5625rem",
    "--font-size-3xl": "1.9375rem",
    "--font-size-4xl": "2.375rem",
    "--font-size-5xl": "2.875rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.44",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.3333",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-bold)",
    "--text-heading-5-leading": "1.4545",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-bold)",
    "--text-heading-6-leading": "1.7778",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4545",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2174",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2632",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.4194",
    "--duration-fast-min": "105ms",
    "--duration-fast": "140ms",
    "--duration-fast-max": "185ms",
    "--duration-medium-min": "240ms",
    "--duration-medium": "320ms",
    "--duration-medium-max": "425ms",
    "--duration-slow-min": "465ms",
    "--duration-slow": "620ms",
    "--duration-slow-max": "825ms",
    "--font-family-body": "\"Segoe UI Variable\", \"Segoe UI\", -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif",
    "--font-family-heading": "\"Segoe UI Variable Display\", \"Arial Narrow\", \"Segoe UI\", Helvetica, Arial, sans-serif",
    "--font-family-code": "\"Cascadia Mono\", \"SF Mono\", Consolas, \"Liberation Mono\", \"Courier New\", monospace",
    "--color-syntax-keyword": "light-dark(#6d28d9, #c4b5fd)",
    "--color-syntax-string": "light-dark(#15803d, #86efac)",
    "--color-syntax-comment": "light-dark(#737373, #8a8a8a)",
    "--color-syntax-number": "light-dark(#b45309, #fbbf24)",
    "--color-syntax-function": "light-dark(#1d4ed8, #93c5fd)",
    "--color-syntax-type": "light-dark(#0e7490, #67e8f9)",
    "--color-syntax-variable": "light-dark(#0a0a0a, #f5f5f5)",
    "--color-syntax-operator": "light-dark(#be185d, #f9a8d4)",
    "--color-syntax-constant": "light-dark(#c2410c, #fdba74)",
    "--color-syntax-tag": "light-dark(#b91c1c, #fca5a5)",
    "--color-syntax-attribute": "light-dark(#a16207, #fde047)",
    "--color-syntax-property": "light-dark(#0f766e, #5eead4)",
    "--color-syntax-punctuation": "light-dark(#8a8a8a, #666666)",
    "--color-syntax-background": "light-dark(#ededed, #1a1a1a)",
    "--color-background-surface": "light-dark(#faf9f6, #101113)",
    "--color-background-body": "light-dark(#f2f0eb, #08090b)",
    "--color-background-card": "light-dark(#faf9f6, #17181b)",
    "--color-background-popover": "light-dark(#faf9f6, #1b1b1d)",
    "--color-background-muted": "light-dark(#e9e7e2, #1d1d1f)",
    "--color-accent": "light-dark(#181818, #ece8e1)",
    "--color-accent-muted": "light-dark(#e8e5df, #292825)",
    "--color-neutral": "light-dark(#00000012, #ffffff1a)",
    "--color-overlay": "light-dark(#000000a6, #000000d9)",
    "--color-overlay-hover": "light-dark(#0000000a, #ffffff0d)",
    "--color-overlay-pressed": "light-dark(#00000014, #ffffff1a)",
    "--color-text-primary": "light-dark(#181818, #f0f1f3)",
    "--color-text-secondary": "light-dark(#575651, #a5a8b0)",
    "--color-text-disabled": "light-dark(#8a8a8a, #666666)",
    "--color-text-accent": "light-dark(#181818, #ece8e1)",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#0a0a0a",
    "--color-on-accent": "light-dark(#faf8f3, #111111)",
    "--color-on-success": "light-dark(#ffffff, #112319)",
    "--color-on-error": "light-dark(#ffffff, #4c0519)",
    "--color-on-warning": "light-dark(#ffffff, #2c2416)",
    "--color-icon-accent": "light-dark(#181818, #ece8e1)",
    "--color-icon-primary": "light-dark(#181818, #ece8e1)",
    "--color-icon-secondary": "light-dark(#575651, #9d9b97)",
    "--color-icon-disabled": "light-dark(#8a8a8a, #666666)",
    "--color-success": "light-dark(#376b50, #8ab7a0)",
    "--color-error": "light-dark(#dc2626, #fb7185)",
    "--color-warning": "light-dark(#84621f, #cfb887)",
    "--color-success-muted": "light-dark(#e1ece5, #1b2b23)",
    "--color-error-muted": "light-dark(#fee2e2, #451a24)",
    "--color-warning-muted": "light-dark(#f2ebdc, #30291c)",
    "--color-border": "light-dark(#1717171a, #ece8e117)",
    "--color-border-emphasized": "light-dark(#86837e, #656460)",
    "--color-skeleton": "light-dark(#dedede, #333333)",
    "--color-shadow": "light-dark(#00000024, #000000a6)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-red": "light-dark(#fee2e2, #450a0a)",
    "--color-border-red": "light-dark(#fca5a5, #dc2626)",
    "--color-icon-red": "light-dark(#dc2626, #fb7185)",
    "--color-text-red": "light-dark(#b91c1c, #fecaca)",
    "--color-background-orange": "light-dark(#ffedd5, #431407)",
    "--color-border-orange": "light-dark(#fdba74, #c2410c)",
    "--color-icon-orange": "light-dark(#c2410c, #fb923c)",
    "--color-text-orange": "light-dark(#9a3412, #fed7aa)",
    "--color-background-yellow": "light-dark(#fef9c3, #422006)",
    "--color-border-yellow": "light-dark(#fde047, #ca8a04)",
    "--color-icon-yellow": "light-dark(#a16207, #facc15)",
    "--color-text-yellow": "light-dark(#854d0e, #fef08a)",
    "--color-background-green": "light-dark(#dcfce7, #14532d)",
    "--color-border-green": "light-dark(#86efac, #15803d)",
    "--color-icon-green": "light-dark(#15803d, #4ade80)",
    "--color-text-green": "light-dark(#166534, #bbf7d0)",
    "--color-background-teal": "light-dark(#ccfbf1, #134e4a)",
    "--color-border-teal": "light-dark(#5eead4, #0f766e)",
    "--color-icon-teal": "light-dark(#0f766e, #2dd4bf)",
    "--color-text-teal": "light-dark(#115e59, #99f6e4)",
    "--color-background-cyan": "light-dark(#cffafe, #164e63)",
    "--color-border-cyan": "light-dark(#67e8f9, #0891b2)",
    "--color-icon-cyan": "light-dark(#0e7490, #67e8f9)",
    "--color-text-cyan": "light-dark(#155e75, #a5f3fc)",
    "--color-background-blue": "light-dark(#dbeafe, #172554)",
    "--color-border-blue": "light-dark(#93c5fd, #1d4ed8)",
    "--color-icon-blue": "light-dark(#1d4ed8, #93c5fd)",
    "--color-text-blue": "light-dark(#1e40af, #bfdbfe)",
    "--color-background-purple": "light-dark(#ede9fe, #2e1065)",
    "--color-border-purple": "light-dark(#c4b5fd, #7c3aed)",
    "--color-icon-purple": "light-dark(#6d28d9, #a78bfa)",
    "--color-text-purple": "light-dark(#5b21b6, #ddd6fe)",
    "--color-background-pink": "light-dark(#fce7f3, #500724)",
    "--color-border-pink": "light-dark(#f9a8d4, #be185d)",
    "--color-icon-pink": "light-dark(#be185d, #f472b6)",
    "--color-text-pink": "light-dark(#9d174d, #fbcfe8)",
    "--color-background-gray": "light-dark(#e0e0e0, #282828)",
    "--color-border-gray": "light-dark(#a3a3a3, #737373)",
    "--color-icon-gray": "light-dark(#171717, #f5f5f5)",
    "--color-text-gray": "light-dark(#171717, #f5f5f5)",
    "--radius-none": "0px",
    "--radius-inner": "6px",
    "--radius-element": "12px",
    "--radius-container": "18px",
    "--radius-page": "42px",
    "--radius-full": "9999px",
    "--shadow-low": "0 1px 2px light-dark(#00000014, #00000080), 0 4px 12px light-dark(#0000000a, #00000066)",
    "--shadow-med": "0 2px 6px light-dark(#0000001a, #00000099), 0 12px 28px light-dark(#00000014, #00000080)",
    "--shadow-high": "0 4px 12px light-dark(#00000024, #000000b3), 0 24px 52px light-dark(#0000001f, #00000099)",
    "--shadow-inset-hover": "inset 0 0 0 2px light-dark(#0000001f, #ffffff24)",
    "--shadow-inset-selected": "inset 0 0 0 2px light-dark(#00000052, #ffffff52)",
    "--shadow-inset-success": "inset 0 0 0 2px light-dark(#0000003d, #ffffff3d)",
    "--shadow-inset-warning": "inset 0 0 0 2px light-dark(#00000033, #ffffff33)",
    "--shadow-inset-error": "inset 0 0 0 2px light-dark(#00000066, #ffffff66)",
    "--radius-chat": "42px",
    "--ease-standard": "cubic-bezier(0.22, 1, 0.36, 1)",
    "--peaks-tracking-label": "0.12em",
    "--peaks-tracking-heading": "-0.03em",
    "--peaks-hero-title-size": "clamp(2.5rem, 3.8vw, 4.5rem)",
    "--peaks-content-width": "1600px",
    "--peaks-sidebar-width": "80px",
    "--peaks-hero-height": "280px",
    "--peaks-artwork-opacity": "0.72",
    "--peaks-avatar-size": "44px",
    "--peaks-account-column": "240px",
    "--peaks-transition-distance": "8px",
    "--peaks-team-ally": "#164638",
    "--peaks-team-self": "#173f69",
    "--peaks-team-enemy": "#5b2630",
    "--peaks-party-yellow": "#f3cf63",
    "--peaks-party-purple": "#b38bf5",
    "--peaks-party-blue": "#344fc4",
    "--peaks-font-game": "\"Bahnschrift\", \"Arial Narrow\", \"Segoe UI\", sans-serif",
    "--peaks-poster-light": "#637cbc",
    "--color-background-inverted": "light-dark(#111111, #ece8e1)",
    "--color-background-error-inverted": "light-dark(#b91c1c, #fb7185)",
    "--color-track": "light-dark(#c7c7c7, #404040)",
    "--focus-outline-color": "var(--color-accent)",
    "--color-data-categorical-blue": "light-dark(#0a0a0a, #f5f5f5)",
    "--color-data-categorical-orange": "light-dark(#1c1c1c, #e0e0e0)",
    "--color-data-categorical-purple": "light-dark(#2e2e2e, #cccccc)",
    "--color-data-categorical-green": "light-dark(#404040, #b8b8b8)",
    "--color-data-categorical-pink": "light-dark(#525252, #a3a3a3)",
    "--color-data-categorical-cyan": "light-dark(#646464, #949494)",
    "--color-data-categorical-red": "light-dark(#737373, #858585)",
    "--color-data-categorical-teal": "light-dark(#595959, #adadad)",
    "--color-data-categorical-brown": "light-dark(#353535, #c2c2c2)",
    "--color-data-categorical-indigo": "light-dark(#171717, #ebebeb)",
    "--color-data-neutral": "light-dark(#737373, #8a8a8a)",
    "--color-data-blue-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-blue-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-blue-3": "light-dark(#707070, #999999)",
    "--color-data-blue-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-blue-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-shamrock-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-shamrock-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-shamrock-3": "light-dark(#707070, #999999)",
    "--color-data-shamrock-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-shamrock-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-orange-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-orange-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-orange-3": "light-dark(#707070, #999999)",
    "--color-data-orange-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-orange-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-pink-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-pink-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-pink-3": "light-dark(#707070, #999999)",
    "--color-data-pink-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-pink-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-purple-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-purple-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-purple-3": "light-dark(#707070, #999999)",
    "--color-data-purple-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-purple-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-red-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-red-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-red-3": "light-dark(#707070, #999999)",
    "--color-data-red-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-red-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-teal-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-teal-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-teal-3": "light-dark(#707070, #999999)",
    "--color-data-teal-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-teal-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-yellow-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-yellow-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-yellow-3": "light-dark(#707070, #999999)",
    "--color-data-yellow-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-yellow-1": "light-dark(#bcbcbc, #5c5c5c)",
    "--color-data-gray-5": "light-dark(#242424, #d4d4d4)",
    "--color-data-gray-4": "light-dark(#4a4a4a, #b8b8b8)",
    "--color-data-gray-3": "light-dark(#707070, #999999)",
    "--color-data-gray-2": "light-dark(#969696, #7a7a7a)",
    "--color-data-gray-1": "light-dark(#bcbcbc, #5c5c5c)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:destructive": {
        "backgroundColor": "var(--color-error)",
        "color": "var(--color-on-error)"
      },
      "base": {
        "borderRadius": "var(--radius-inner)",
        "fontWeight": "var(--font-weight-semibold)"
      }
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "var(--color-accent)",
        "color": "var(--color-on-accent)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:success": {
        "backgroundColor": "var(--color-success)",
        "color": "var(--color-on-success)"
      },
      "variant:warning": {
        "backgroundColor": "var(--color-warning)",
        "color": "var(--color-on-warning)"
      },
      "variant:error": {
        "backgroundColor": "var(--color-error)",
        "color": "var(--color-on-error)"
      },
      "variant:red": {
        "backgroundColor": "var(--color-background-red)",
        "color": "var(--color-text-red)"
      },
      "variant:orange": {
        "backgroundColor": "var(--color-background-orange)",
        "color": "var(--color-text-orange)"
      },
      "variant:yellow": {
        "backgroundColor": "var(--color-background-yellow)",
        "color": "var(--color-text-yellow)"
      },
      "variant:green": {
        "backgroundColor": "var(--color-background-green)",
        "color": "var(--color-text-green)"
      },
      "variant:teal": {
        "backgroundColor": "var(--color-background-teal)",
        "color": "var(--color-text-teal)"
      },
      "variant:cyan": {
        "backgroundColor": "var(--color-background-cyan)",
        "color": "var(--color-text-cyan)"
      },
      "variant:blue": {
        "backgroundColor": "var(--color-background-blue)",
        "color": "var(--color-text-blue)"
      },
      "variant:purple": {
        "backgroundColor": "var(--color-background-purple)",
        "color": "var(--color-text-purple)"
      },
      "variant:pink": {
        "backgroundColor": "var(--color-background-pink)",
        "color": "var(--color-text-pink)"
      },
      "variant:gray": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      }
    },
    "statusdot": {
      "variant:success": {
        "backgroundColor": "var(--color-success)"
      },
      "variant:warning": {
        "backgroundColor": "var(--color-warning)"
      },
      "variant:error": {
        "backgroundColor": "var(--color-error)"
      },
      "variant:accent": {
        "backgroundColor": "var(--color-accent)"
      }
    },
    "banner": {
      "status:info": {
        "--color-accent-muted": "var(--color-neutral)",
        "--color-text-primary": "inherit",
        "--color-text-secondary": "inherit",
        "--color-accent": "inherit"
      },
      "status:success": {
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
        "--color-success": "var(--color-text-green)"
      },
      "status:warning": {
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)"
      },
      "status:error": {
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
        "--color-error": "var(--color-text-red)"
      }
    },
    "switch": {
      "base": {
        "--color-background-gray": "var(--color-border-emphasized)"
      }
    },
    "progressbar": {
      "base": {
        "--color-background-muted": "var(--color-neutral)"
      },
      "variant:accent": {
        "--color-accent": "inherit"
      },
      "variant:success": {
        "--color-success": "inherit"
      },
      "variant:warning": {
        "--color-warning": "inherit"
      },
      "variant:error": {
        "--color-error": "inherit"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "side-nav-item": {
      "base": {
        "borderRadius": "var(--radius-inner)"
      },
      "selected": {
        "backgroundColor": "var(--color-background-muted)",
        "color": "var(--color-text-primary)"
      }
    },
    "tab": {
      "base": {
        "borderRadius": "var(--radius-inner)"
      },
      "selected": {
        "color": "var(--color-text-primary)"
      }
    },
    "tab-indicator": {
      "base": {
        "backgroundColor": "var(--color-accent)"
      }
    },
    "radio-indicator": {
      "checked": {
        "backgroundColor": "var(--color-accent)",
        "borderColor": "var(--color-accent)"
      }
    },
    "radio-indicator-dot": {
      "base": {
        "backgroundColor": "var(--color-accent)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "#ece8e1",
      "--color-accent-muted": "#292825",
      "--color-on-accent": "#111111",
      "--color-text-accent": "#ece8e1",
      "--color-icon-accent": "#ece8e1"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "#181818",
      "--color-accent-muted": "#e8e5df",
      "--color-on-accent": "#faf8f3",
      "--color-text-accent": "#181818",
      "--color-icon-accent": "#181818"
    }
  },

};
