"""Fixed vocabulary for local diagnostics; free-form content is never retained.

Add new diagnostic event names/enum values here deliberately. Unknown messages,
fields and values are withheld, including raw exceptions, URLs and identifiers.
This local vocabulary is not uploaded as telemetry.
"""

from __future__ import annotations

import re

# Explicit names from the application's diagnostic call sites, not a prefix rule.
SAFE_EVENTS = frozenset(
    [
        "account_onboarding.browser.cancelled",
        "account_onboarding.browser.capture.complete",
        "account_onboarding.browser.capture.failed",
        "account_onboarding.browser.failed",
        "account_onboarding.browser.identity.verified",
        "account_onboarding.browser.start",
        "account_onboarding.local.complete",
        "account_onboarding.local.discovery.failed",
        "account_onboarding.local.discovery.pending",
        "account_onboarding.local.discovery.verified",
        "account_onboarding.local.entitlements.request",
        "account_onboarding.local.failed",
        "account_onboarding.local.identity.verified",
        "account_onboarding.local.session_capture.complete",
        "account_onboarding.local.session_capture.identity_mismatch",
        "account_onboarding.local.session_capture.start",
        "account_onboarding.local.session_capture.unavailable",
        "account_onboarding.local.start",
        "account_onboarding.process_detection.complete",
        "account_onboarding.process_detection.failed",
        "account_onboarding.start",
        "bridge.account.background_refresh_failed",
        "bridge.account.persisted",
        "bridge.account.refresh_complete",
        "bridge.account.refresh_league_unavailable",
        "bridge.account.refresh_local_unavailable",
        "bridge.account.refresh_remote_unavailable",
        "bridge.account.region_recovered",
        "bridge.account.region_recovery_unavailable",
        "bridge.account.secret_saved",
        "bridge.activity.complete",
        "bridge.activity.failed",
        "bridge.activity.start",
        "bridge.command.complete",
        "bridge.command.failed",
        "bridge.command.start",
        "bridge.database.load_failed",
        "bridge.match.final_refresh_failed",
        "bridge.profile_reset.complete",
        "bridge.profile_reset.failed",
        "bridge.profile_reset.recovered",
        "bridge.provider.configure_failed",
        "bridge.provider.configured",
        "bridge.provider.key_load_failed",
        "bridge.riot_qr.approval.complete",
        "bridge.riot_qr.approval.failed",
        "bridge.riot_qr.approval.session_binding_changed",
        "bridge.riot_qr.capture.decode_complete",
        "bridge.riot_qr.capture.decode_start",
        "bridge.riot_qr.capture.failed",
        "bridge.riot_qr.capture.invalid_payload",
        "bridge.riot_qr.capture.received",
        "bridge.riot_qr.session.cookies_rotated",
        "bridge.riot_qr.session.details_failed",
        "bridge.riot_qr.session.details_verified",
        "bridge.riot_qr.session.identity_bound",
        "bridge.riot_qr.session.identity_mismatch",
        "bridge.riot_qr.session.mint_failed",
        "bridge.riot_qr.session.mint_start",
        "bridge.services.open_complete",
        "bridge.services.open_failed",
        "bridge.services.open_start",
        "bridge.session_import.browser.cancelled",
        "bridge.session_import.browser.cookies_captured",
        "bridge.session_import.browser.failed",
        "bridge.session_import.browser.identity_mismatch",
        "bridge.session_import.browser.identity_received",
        "bridge.session_import.browser.start",
        "bridge.session_import.browser.requested",
        "bridge.session_import.failed",
        "bridge.session_import.local.complete",
        "bridge.session_import.local.unavailable",
        "bridge.session_import.saved",
        "bridge.session_import.start",
        "bridge.session_maintenance.complete",
        "bridge.session_maintenance.deferred",
        "bridge.session_maintenance.reauthentication_required",
        "bridge.session_maintenance.start",
        "current_game.owned_league.unavailable",
        "current_game.owned_region.complete",
        "current_game.owned_region.start",
        "current_game.owned_region.unavailable",
        "current_game.owned_snapshot.complete",
        "current_game.owned_snapshot.level_unavailable",
        "current_game.owned_snapshot.start",
        "current_game.owned_snapshot.unavailable",
        "current_game.valorant_auth.entitlements_retry",
        "current_game.valorant_auth.product_session_unavailable",
        "current_game.valorant_auth.ready",
        "current_game.valorant_auth.unavailable",
        "current_game.valorant_names.unavailable",
        "current_game.valorant_party.enrichment_unavailable",
        "current_game.valorant_party.unavailable",
        "current_game.valorant_presence.unavailable",
        "current_game.valorant_profiles.unavailable",
        "current_game.valorant_ranks.unavailable",
        "diagnostics.ready",
        "riot_browser.authenticated",
        "riot_browser.cancelled",
        "riot_browser.failed",
        "riot_browser.launched",
        "riot_browser.reusable_session_loaded",
        "riot_browser.start",
        "riot_account_session.response",
        "riot_account_session.rejected",
        "riot_account_session.handoff",
        "riot_account_session.prompt",
        "riot_account_session.redirect",
        "riot_account_session.callback",
        "riot_local.request.complete",
        "riot_local.request.failed",
        "riot_mobile_totp.confirm.complete",
        "riot_mobile_totp.confirm.csrf_refresh.complete",
        "riot_mobile_totp.confirm.csrf_refresh.failed",
        "riot_mobile_totp.confirm.csrf_refresh.start",
        "riot_mobile_totp.confirm.enable_failed",
        "riot_mobile_totp.confirm.enable_request",
        "riot_mobile_totp.confirm.enable_secret_valid",
        "riot_mobile_totp.confirm.factors_rechecked",
        "riot_mobile_totp.confirm.failed",
        "riot_mobile_totp.confirm.identity_reverified",
        "riot_mobile_totp.confirm.persistence_failed",
        "riot_mobile_totp.confirm.riot_request_failed",
        "riot_mobile_totp.confirm.seed_persisted",
        "riot_mobile_totp.confirm.start",
        "riot_mobile_totp.confirm.verify_failed",
        "riot_mobile_totp.confirm.verify_request",
        "riot_mobile_totp.confirmation_expired",
        "riot_mobile_totp.prepare.browser_failed",
        "riot_mobile_totp.prepare.cancelled",
        "riot_mobile_totp.prepare.complete",
        "riot_mobile_totp.prepare.csrf_refresh.complete",
        "riot_mobile_totp.prepare.csrf_refresh.failed",
        "riot_mobile_totp.prepare.csrf_refresh.start",
        "riot_mobile_totp.prepare.factors_checked",
        "riot_mobile_totp.prepare.failed",
        "riot_mobile_totp.prepare.identity_verified",
        "riot_mobile_totp.prepare.riot_request_failed",
        "riot_mobile_totp.prepare.session_failed",
        "riot_mobile_totp.prepare.start",
        "riot_qr.cookie_cleanup.failed",
        "riot_qr.request.failed",
        "riot_qr.request.rejected",
        "riot_session.authorization.complete",
        "riot_session.authorization.invalid_response",
        "riot_session.authorization.reauthentication_required",
        "riot_session.authorization.rejected",
        "riot_session.authorization.start",
        "riot_session.authorization.transport_failed",
        "riot_session.cookies.read_complete",
        "riot_session.cookies.read_start",
        "riot_session.identity.complete",
        "riot_session.identity.rejected",
        "riot_session.identity.start",
        "riot_session.identity.transport_failed",
        "riot_session.import.complete",
        "riot_session.import.start",
        "riot_session.offline_authorization.unavailable",
        "riot_session.region.complete",
        "riot_session.region.unavailable",
        "riot_session.settings.available",
        "riot_session.settings.validate_start",
        "riot_session.token.complete",
        "riot_session.token.rejected",
        "search.valorant.complete",
        "search.valorant.unavailable",
        "valorant.account_level.complete",
        "valorant.account_level.unavailable",
        "valorant.live_names.complete",
        "valorant.live_names.unavailable",
        "valorant.live_ranks.complete",
        "valorant.match_history.complete",
        "valorant.match_history.retry",
        "valorant.match_history.start",
        "valorant.match_history.unavailable",
        "valorant.party.unavailable",
        "valorant.rank.complete",
        "valorant.rank.fallback_unavailable",
        "valorant.rank.primary_requires_active_season",
        "valorant.rank.primary_unavailable",
        "valorant.rank.start",
        "valorant.remote.request.complete",
        "valorant.remote.request.start",
        "valorant.remote.request.unavailable",
        "diagnostics.redacted",
    ]
)

ERROR_TYPES = frozenset(
    [
        "AccountBindingError",
        "AccountIdentityMismatchError",
        "AccountOnboardingCancelledError",
        "AccountOnboardingError",
        "AccountOnboardingUnavailableError",
        "ApprovalRequired",
        "CredentialsUnavailable",
        "InvalidPinError",
        "LockfileError",
        "QRParseError",
        "RiotApiError",
        "RiotApiTransportError",
        "RiotBrowserLoginError",
        "RiotBrowserUnavailableError",
        "RiotAccountSessionError",
        "RiotAccountSessionChallengeError",
        "RiotAccountSessionHttpError",
        "RiotClientError",
        "RiotClientUnavailable",
        "RiotConnectError",
        "RiotConnectHTTPError",
        "RiotConnectTransportError",
        "RiotMfaError",
        "RiotMfaHttpError",
        "RiotMobileTotpConfirmationError",
        "RiotMobileTotpIdentityMismatchError",
        "RiotMobileTotpPersistenceError",
        "RiotMobileTotpPrerequisiteError",
        "RiotMobileTotpSetupCancelledError",
        "RiotMobileTotpSetupError",
        "RiotSessionImportError",
        "SeedParseError",
        "SessionAuthorizationError",
        "SessionAuthorizationHTTPError",
        "SessionDetailsRequired",
        "SessionExpired",
        "SessionReauthenticationRequired",
        "SessionSettingsError",
        "UnsupportedPlatformError",
        "UnsupportedRiotRegion",
        "UnsupportedValorantApiError",
        "ValorantMetadataError",
        "VaultAlreadyInitializedError",
        "VaultBackoffError",
        "VaultCorruptedError",
        "VaultError",
        "VaultKeyUnavailableError",
        "VaultLockedError",
        "VaultNotInitializedError",
        "_SessionIdentityMismatchError",
        "_SessionImportBindingError",
        "AssertionError",
        "AttributeError",
        "ConnectionError",
        "ConnectionResetError",
        "FileNotFoundError",
        "HTTPError",
        "IndexError",
        "JSONDecodeError",
        "KeyError",
        "OSError",
        "PermissionError",
        "RuntimeError",
        "Timeout",
        "TimeoutError",
        "TypeError",
        "UnicodeDecodeError",
        "UnicodeEncodeError",
        "ValueError",
        "ConnectTimeout",
        "ReadTimeout",
        "SSLError",
        "ProxyError",
        "RequestException",
        "InvalidToken",
        "MissingPayload",
        "Exception",
        "CancelledError",
        "BrokenPipeError",
    ]
)

_ENUM_FIELDS = {
    "command": frozenset(
        [
            "state",
            "activity",
            "refresh",
            "search",
            "settings",
            "add_account",
            "remove_account",
            "set_account_icon",
            "import_session",
            "connect_riot_client",
            "connect_riot_qr_image",
            "pin",
            "lock",
            "change_pin",
            "reset_application",
            "api_key",
            "prepare_totp_setup",
            "confirm_totp_setup",
            "enable_riot_mfa",
            "cancel_totp_setup",
            "copy_totp",
            "toggle_follow",
            "toggle_watchlist",
            "scan_qr",
            "unknown",
        ]
    ),
    "error_type": ERROR_TYPES,
    "level": frozenset(["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]),
    "pin_mode": frozenset(["create", "confirm", "unlock"]),
    "source": frozenset(
        [
            "local_client",
            "browser",
            "local",
            "saved_session",
            "primary",
            "primary_active_season",
            "competitive_updates",
            "unknown",
        ]
    ),
    "fallback": frozenset({"browser"}),
    "game": frozenset(
        {"valorant", "league", "league of legends", "tft", "teamfight tactics", "none"}
    ),
    "method": frozenset(
        [
            "GET",
            "POST",
            "PUT",
            "PATCH",
            "DELETE",
            "HEAD",
            "OPTIONS",
            "access_token",
            "session",
            "unknown",
        ]
    ),
    "operation": frozenset(["session_info", "session_approval", "unknown"]),
    "service": frozenset(["pd", "glz", "shared"]),
    "response_type": frozenset(["auth", "multifactor", "response"]),
    "grant": frozenset(["refresh_token", "authorization_code"]),
    "stage": frozenset([
        "account_home", "account_login", "account_authorize", "account_callback",
        "authenticator_login", "authenticator_page", "authenticator_session",
    ]),
    "prompt": frozenset(["auth", "re-auth", "multifactor", "success", "error", "unknown"]),
    "target": frozenset([
        "account_home", "account_login", "account_authorize", "account_callback",
        "authenticator_login", "authenticator_page", "unknown",
    ]),
    "state": frozenset(
        ["ready", "window_not_found", "window_capture_failed", "capture_error", "invalid"]
    ),
    "reason": frozenset(
        [
            "authentication",
            "browser_challenge",
            "http_rejected",
            "interactive_auth",
            "frontend_context",
            "callback_fields",
            "callback_state",
            "callback_issuer",
            "callback_session_state",
            "credentials",
            "entitlements",
            "entitlements_not_ready",
            "entitlements_payload",
            "identity_mismatch",
            "invalid_payload",
            "local_client",
            "local_request",
            "lockfile",
            "no_data",
            "no_importer",
            "no_rank_updates",
            "precondition",
            "region_payload",
            "region_unknown",
            "remote_client",
            "requested",
            "service_routes",
            "service_version",
            "subject",
            "timeout",
            "unsupported_region",
            "valorant_session_inactive",
            "window_closed",
            "invalid_grant",
            "invalid_client",
            "unauthorized_client",
            "invalid_scope",
            "other",
            "unknown",
        ]
    ),
}
_REGIONS = frozenset(
    [
        "BR",
        "EUN",
        "EUW",
        "JP",
        "KR",
        "LA1",
        "LA2",
        "NA",
        "OC",
        "PH",
        "RU",
        "SG",
        "TH",
        "TR",
        "TW",
        "VN",
        "ME",
        "br",
        "eun",
        "euw",
        "jp",
        "kr",
        "la1",
        "la2",
        "na",
        "oc",
        "ph",
        "ru",
        "sg",
        "th",
        "tr",
        "tw",
        "vn",
        "me",
        "eu",
        "ap",
        "latam",
        "pbe",
        "unknown",
    ]
)
for _field in ("region", "league", "valorant"):
    _ENUM_FIELDS[_field] = _REGIONS

_COUNTER_FIELDS = frozenset(
    [
        "account_cookie_count",
        "attempt",
        "auth_cookie_count",
        "cookie_count",
        "count",
        "detail_failures",
        "failures",
        "limit",
        "match_count",
        "rank_count",
        "requested",
        "resolved",
        "rotated_cookie_count",
        "unavailable",
        "updated",
    ]
)
_BOOLEAN_FIELDS = frozenset(
    [
        "client_detected",
        "email_enabled",
        "has_issuer",
        "has_error",
        "has_session_state",
        "executable_verified",
        "level_available",
        "lockfile_present",
        "match_detected",
        "process_running",
        "refresh_token_issued",
        "reusable_session",
        "reusable_session_saved",
        "riotmobile_enabled",
        "supported",
        "valid_account",
        "valorant_active",
        "verified",
    ]
)
_FIELD = re.compile(r"(?:^|\s)([a-z_]+)=(.*?)(?=\s[a-z_]+=|$)", re.DOTALL)


def sanitize_diagnostic_message(message: str) -> str:
    """Keep known event names and approved scalar metadata, never arbitrary text."""
    if len(message) > 16_384:
        return "diagnostics.redacted"
    event, _, metadata = message.partition(" ")
    if event not in SAFE_EVENTS:
        return "diagnostics.redacted"
    output = [event]
    redacted = False
    consumed = 0
    seen: set[str] = set()
    for match in _FIELD.finditer(metadata):
        if metadata[consumed : match.start()].strip():
            redacted = True
        consumed = match.end()
        key, value = match.group(1), match.group(2).strip()
        approved = value in _ENUM_FIELDS.get(key, ())
        if key in _BOOLEAN_FIELDS:
            approved = value in {"True", "False", "true", "false"}
        if key in _COUNTER_FIELDS:
            approved = bool(re.fullmatch(r"[0-9]{1,6}", value)) and int(value) <= 100_000
        if key == "status":
            approved = value in {"unknown", "0"} or (bool(re.fullmatch(r"[1-5][0-9]{2}", value)))
        if approved and key not in seen:
            output.append(f"{key}={value}")
            seen.add(key)
        else:
            redacted = True
    if metadata[consumed:].strip():
        redacted = True
    if redacted:
        output.append("redacted=true")
    return " ".join(output)
