#!/usr/bin/env python3
"""Build the Peaks desktop application with PyInstaller.

The supported artifact is an onedir build. Keeping Qt and native helpers
outside a one-file extraction step makes startup predictable on
Windows and gives endpoint scanners a stable set of files to inspect.

This script deliberately does not cross-build. Run it with a Python and
dependencies native to the target OS/architecture (the CI workflow does
this on Windows x64 and macOS arm64).

Examples::

    uv run python scripts/build.py --clean --smoke
    uv run python scripts/build.py --clean --sign-hook packaging/sign.ps1
    uv run python scripts/build.py --clean --release --sign-hook packaging/sign.ps1

The optional signing hook receives the produced ``dist/Peaks`` directory on
Windows or ``dist/Peaks.app`` on macOS as its only argument. With
``--installer`` it is invoked a second time with the installer executable.
It is never run unless explicitly selected with ``--sign-hook`` or
``PEAKS_SIGN_HOOK``. ``--release`` makes signing mandatory and fails before
PyInstaller starts when no valid hook is configured; this keeps local unsigned
development builds possible while making release CI fail closed.

On Windows, pass ``--installer`` to compile ``packaging/Peaks.iss`` with the
native Inno Setup 6 compiler (ISCC). The installer is per-user and is never
attempted on macOS.
"""

from __future__ import annotations

import argparse
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "packaging" / "Peaks.spec"
INSTALLER_SPEC = ROOT / "packaging" / "Peaks.iss"
DIST = ROOT / "dist"


def _project_version() -> str:
    """Read the version from pyproject without importing application code."""

    with (ROOT / "pyproject.toml").open("rb") as handle:
        project = tomllib.load(handle).get("project", {})
    version = project.get("version")
    if not isinstance(version, str) or not version.strip():
        raise RuntimeError("project.version is missing from pyproject.toml")
    return version.strip()


def _windows_version_tuple(version: str) -> tuple[int, int, int, int]:
    """Return the four numeric components required by a Windows resource."""

    numbers = [int(item) for item in re.findall(r"\d+", version)[:4]]
    numbers.extend([0] * (4 - len(numbers)))
    return tuple(numbers[:4])  # type: ignore[return-value]


def _write_version_info(path: Path, version: str) -> None:
    """Write a PyInstaller version resource for Windows executable metadata."""

    major, minor, patch, revision = _windows_version_tuple(version)
    content = f"""# UTF-8
# Generated by scripts/build.py; do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {revision}),
    prodvers=({major}, {minor}, {patch}, {revision}),
    mask=0x3F, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
    date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Peaks contributors'),
      StringStruct('FileDescription', 'Peaks Riot account companion'),
      StringStruct('FileVersion', '{version}'),
      StringStruct('InternalName', 'Peaks'),
      StringStruct('OriginalFilename', 'Peaks.exe'),
      StringStruct('ProductName', 'Peaks'),
      StringStruct('ProductVersion', '{version}')
    ])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    path.write_text(content, encoding="utf-8")


def _run(command: list[str], *, cwd: Path = ROOT, env: dict[str, str] | None = None) -> None:
    """Run a command with a concise, useful log line."""

    printable = " ".join(shlex.quote(part) for part in command)
    print(f"[build] {printable}")
    subprocess.run(command, cwd=cwd, env=env, check=True)


def _clean_outputs() -> None:
    """Remove only known build outputs before a reproducible build."""

    for path in (DIST, ROOT / "build"):
        if path.exists():
            print(f"[build] removing {path}")
            shutil.rmtree(path)


def _artifact_path() -> Path:
    if sys.platform == "win32":
        return DIST / "Peaks" / "Peaks.exe"
    if sys.platform == "darwin":
        return DIST / "Peaks.app"
    return DIST / "Peaks" / "Peaks"


def _find_inno_setup() -> Path:
    """Resolve the native Inno Setup 6 compiler without downloading software."""

    configured = os.environ.get("ISCC_EXE") or os.environ.get("INNO_SETUP_COMPILER")
    candidates: list[Path] = []
    if configured:
        candidates.append(Path(configured).expanduser())
    for executable in ("ISCC.exe", "iscc"):
        located = shutil.which(executable)
        if located:
            candidates.append(Path(located))
    for variable in ("ProgramFiles", "ProgramFiles(x86)"):
        program_files = os.environ.get(variable)
        if program_files:
            candidates.append(Path(program_files) / "Inno Setup 6" / "ISCC.exe")

    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    raise FileNotFoundError(
        "Inno Setup 6 compiler (ISCC.exe) not found. Install Inno Setup 6 or "
        "set ISCC_EXE to its compiler path."
    )


def _build_installer(version: str) -> Path:
    """Compile the per-user Windows installer and return its executable."""

    if sys.platform != "win32":
        raise RuntimeError("--installer is supported only on native Windows builds")
    if not INSTALLER_SPEC.is_file():
        raise FileNotFoundError(f"Inno Setup script not found: {INSTALLER_SPEC}")

    compiler = _find_inno_setup()
    _run(
        [
            str(compiler),
            "/Qp",
            f"/DMyAppVersion={version}",
            str(INSTALLER_SPEC),
        ]
    )
    output_dir = DIST / "installer"
    expected = output_dir / f"Peaks-Setup-{version}.exe"
    if expected.is_file():
        return expected
    # Keep the script tolerant of an Inno Setup filename normalization (for
    # example, a pre-release version containing a separator).
    candidates = sorted(output_dir.glob("Peaks-Setup-*.exe"))
    if len(candidates) == 1:
        return candidates[0]
    raise FileNotFoundError(f"Inno Setup completed without producing {expected}")


def _resolve_sign_hook(hook: str | None) -> Path | None:
    """Resolve the configured signing hook without exposing secret values."""

    hook_value = hook or os.environ.get("PEAKS_SIGN_HOOK")
    if not hook_value:
        return None

    hook_path = Path(hook_value).expanduser()
    if not hook_path.is_absolute():
        hook_path = ROOT / hook_path
    if not hook_path.is_file():
        raise FileNotFoundError(f"signing hook does not exist: {hook_path}")
    return hook_path.resolve()


def _sign_target(target: Path, hook: str | None, *, required: bool = False) -> None:
    """Run the signing hook for an artifact, optionally requiring it."""

    hook_path = _resolve_sign_hook(hook)
    if hook_path is None:
        if required:
            raise RuntimeError(
                "release builds require a signing hook; pass --sign-hook or "
                "set PEAKS_SIGN_HOOK"
            )
        print("[build] signing hook not configured; leaving binaries unsigned")
        return

    suffix = hook_path.suffix.lower()
    if sys.platform == "win32" and suffix in {".cmd", ".bat"}:
        command = ["cmd", "/d", "/c", str(hook_path), str(target)]
    elif sys.platform == "win32" and suffix == ".ps1":
        command = [
            "powershell",
            "-NoLogo",
            "-NoProfile",
            "-NonInteractive",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(hook_path),
            str(target),
        ]
    else:
        command = [str(hook_path), str(target)]
    _run(command)


def _smoke_launch(target: Path, timeout: float) -> None:
    """Start the frozen GUI long enough to catch import/resource failures."""

    executable = target
    if sys.platform == "darwin":
        executable = target / "Contents" / "MacOS" / "Peaks"
    if not executable.is_file():
        raise FileNotFoundError(f"frozen executable not found: {executable}")

    env = os.environ.copy()
    # This permits a startup smoke test on a headless macOS runner. The
    # variable is harmless on Windows and ignored by non-Qt code.
    env.setdefault("QT_QPA_PLATFORM", "offscreen")
    # Peaks exposes this bounded test-only exit path so a smoke run can prove
    # the QML engine reached its event loop without leaving a GUI process
    # behind on a CI runner.
    env.setdefault("PEAKS_SMOKE_EXIT_MS", "1500")
    print(f"[build] smoke launching {executable}")
    process = subprocess.Popen([str(executable)], cwd=ROOT, env=env)
    deadline = time.monotonic() + timeout
    try:
        while process.poll() is None and time.monotonic() < deadline:
            time.sleep(0.1)
        return_code = process.poll()
        if return_code is None:
            # A GUI that remains alive is the expected success state. Stop it
            # so CI never hangs waiting for a user to close the window.
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=5)
            return
        if return_code != 0:
            raise RuntimeError(f"frozen app exited during smoke test ({return_code})")
    finally:
        if process.poll() is None:
            process.kill()
            process.wait(timeout=5)


def build(
    *,
    clean: bool,
    smoke: bool,
    smoke_timeout: float,
    sign_hook: str | None,
    installer: bool = False,
    release: bool = False,
) -> Path:
    """Build and optionally smoke-test Peaks, returning its artifact path."""

    if installer and sys.platform != "win32":
        raise RuntimeError("--installer is supported only on native Windows builds")
    # Resolve this before cleaning or invoking PyInstaller. A release build
    # should fail fast when CI has not supplied its protected signing setup.
    resolved_sign_hook = _resolve_sign_hook(sign_hook)
    if release and resolved_sign_hook is None:
        raise RuntimeError(
            "release builds require a signing hook; pass --sign-hook or "
            "set PEAKS_SIGN_HOOK"
        )
    if not SPEC.is_file():
        raise FileNotFoundError(f"PyInstaller spec not found: {SPEC}")
    if clean:
        _clean_outputs()

    version = _project_version()
    pyinstaller = [sys.executable, "-m", "PyInstaller"]
    with tempfile.TemporaryDirectory(prefix="peaks-pyinstaller-") as temp_dir:
        temp = Path(temp_dir)
        version_file = temp / "version_info.txt"
        _write_version_info(version_file, version)
        env = os.environ.copy()
        env["PEAKS_VERSION_FILE"] = str(version_file)
        env["PEAKS_VERSION"] = version
        _run(
            [
                *pyinstaller,
                "--clean",
                "--noconfirm",
                "--workpath",
                str(temp / "work"),
                "--distpath",
                str(DIST),
                str(SPEC),
            ],
            env=env,
        )

    target = _artifact_path()
    if not target.exists():
        raise FileNotFoundError(f"PyInstaller completed without producing {target}")
    _sign_target(target, str(resolved_sign_hook) if resolved_sign_hook else None, required=release)
    if smoke:
        _smoke_launch(target, smoke_timeout)
    if installer:
        installer_target = _build_installer(version)
        # The installer is a separately produced PE and must be signed after
        # Inno Setup compiles it; signing only the onedir executable is not
        # sufficient for a Windows release.
        _sign_target(
            installer_target,
            str(resolved_sign_hook) if resolved_sign_hook else None,
            required=release,
        )
        print(f"[build] installer: {installer_target}")
        return installer_target
    print(f"[build] done: {target}")
    return target


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="remove dist/ and build/ before packaging",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="keep existing outputs (overrides --clean)",
    )
    parser.add_argument(
        "--smoke",
        action="store_true",
        help="launch the frozen application briefly after packaging",
    )
    parser.add_argument(
        "--smoke-timeout",
        type=float,
        default=8.0,
        metavar="SECONDS",
        help="maximum startup wait for --smoke (default: 8)",
    )
    parser.add_argument(
        "--sign-hook",
        metavar="PATH",
        help="optional executable/script that signs the produced artifact",
    )
    parser.add_argument(
        "--installer",
        action="store_true",
        help="compile the per-user Inno Setup installer (native Windows only)",
    )
    parser.add_argument(
        "--release",
        action="store_true",
        help="require the configured signing hook before producing artifacts",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.smoke_timeout <= 0:
        raise SystemExit("--smoke-timeout must be positive")
    build(
        clean=args.clean and not args.no_clean,
        smoke=args.smoke,
        smoke_timeout=args.smoke_timeout,
        sign_hook=args.sign_hook,
        installer=args.installer,
        release=args.release,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
